pipeline{
   agent any
   stages{
    stage('Build'){
        steps{

         
           sh 'ls'
             sh 'cd java && cd mi-proyecto && mvn clean install'
             sh 'ls'

        }
    }
     stage('Test'){
        steps{
       

               dir('java/mi-proyecto') {
        sh 'ls'
        sh 'mvn test'
    }
             
            
        }
    }
     stage('Deploy'){
        steps{
         
            echo "Simulando un despliegue a un servidor de aplicaciones"
        }
    }

   }
  
  post{
    always{
     echo "Siempre se ejecuta"
    }
    success{
     echo "Exito este bloque se ejecuta"
    }
    failure{
     echo "Este bloque se ejecuta si el pipeline falla"
    }

   }

}