pipeline{
   agent any
   stages{
    stage('Build'){
        steps{
           
             sh 'cd mi-proyecto'
            sh 'mvn clean install'
        }
    }
     stage('Test'){
        steps{
            sh 'mvn test'
        }
    }
     stage('Deploy'){
        steps{
         
            echo "Simulando un despliegue a un servidor de aplicaciones"
        }
    }

   }
  
  post{
    always{
     echo "Siempre se ejecuta"
    }
    success{
     echo "Exito este bloque se ejecuta"
    }
    failure{
     echo "Este bloque se ejecuta si el pipeline falla"
    }

   }

}